language: node_js
node_js:
    - "node"

after_script:
    - gitbook build
    - cd ./_book
    - git init
    - git config user.name "${USER_NAME}"
    - git config user.email "${USER_EMAIL}"
    - cp ../CNAME .
    - git add .
    - git commit -m "publish gitbook"
    - git push --force --quiet "https://${7b8347057f8590830ad8524db8213751cdd44e7d}@${github.com/Laido-LiuYue/mybook}" master:{gh-pages}

branches:
    only:
        - master
